name: Java CI

on:
  pull_request:
    branches: [ "main", "release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: friendly_blood
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install -y maven

    - name: Build with Maven
      run: mvn clean package
